#include "Main.h"


static luaL_Reg cMethods[] = {
	{ "Init", init },
	{ "Quit", quit },
	{ "GetBasePath", getBasePath },
	{ "SetClipboardText", setClipboardText },
	{ "GetClipboardText", getClipboardText },
	{ "GetPlatform", getPlatform },
	{ "GetSystemRAM", getSystemRAM },
	{ "ShowMessageBox", showMessageBox},
	{ "CreateWindow", createWindow },
	{ "CloseWindow", closeWindow },
	{ "SetWindowTitle", setWindowTitle },
	{ "GetWindowTitle", getWindowTitle },
	{ "SetWindowMode", setWindowMode },
	{ "SetWindowResizable", setWindowResizable },
	{ "SetWindowOpacity", setWindowOpacity },
	{ "SetWindowSize", setWindowSize },
	{ "GetWindowSize", getWindowSize },
	{ "SetWindowMaxSize", setWindowMaxSize },
	{ "GetWindowMaxSize", getWindowMaxSize },
	{ "SetWindowMinSize", setWindowMinSize },
	{ "GetWindowMinSize", getWindowMinSize },
	{ "SetWindowPosition", setWindowPosition },
	{ "GetWindowPosition", getWindowPosition },
	{ "Clear", clear },
	{ "SetCursorShow", setCursorShow },
	{ "GetCursorPosition", getCursorPosition },
	{ "GetScrollValue", getScrollValue },
	{ "LoadImage", loadImage },
	{ "LoadColorKeyImage", loadColorKeyImage },
	{ "UnloadImage", unloadImage },
	{ "SetImageAlpha", setImageAlpha },
	{ "GetImageSize", getImageSize },
	{ "ShowImage", showImage },
	{ "ShowRotateImage", showRotateImage },
	{ "ShowReshapeImage", showReshapeImage },
	{ "ShowRotateReshapeImage", showRotateReshapeImage },
	{ "SetDrawColor", setDrawColor },
	{ "GetDrawColor", getDrawColor },
	{ "Point", point },
	{ "Line", line },
	{ "ThickLine", thickLine },
	{ "Rectangle", rectangle },
	{ "FillRectangle", fillRectangle },
	{ "RoundRectangle", roundRectangle },
	{ "FillRoundRectangle", fillRoundRectangle },
	{ "Circle", circle },
	{ "FillCircle", fillCircle },
	{ "Ellipse", ellipse },
	{ "FillEllipse", fillEllipse },
	{ "Pie", pie },
	{ "FillPie", fillPie },
	{ "Triangle", triangle },
	{ "FillTriangle", fillTriangle },
	{ "Update", update },
	{ "LoadMusic", loadMusic },
	{ "UnloadMusic", unloadMusic },
	{ "PlayMusic", playMusic },
	{ "FadeInMusic", fadeInMusic },
	{ "FadeOutMusic", fadeOutMusic },
	{ "SetMusicVolume", setMusicVolume },
	{ "GetMusicVolume", getMusicVolume },
	{ "PauseMusic", pauseMusic },
	{ "ResumeMusic", resumeMusic },
	{ "RewindMusic", rewindMusic },
	{ "GetMusicType", getMusicType },
	{ "LoadSound", loadSound },
	{ "UnloadSound", unloadSound },
	{ "PlaySound", playSound },
	{ "LoadFont", loadFont },
	{ "UnloadFont", unloadFont },
	{ "SetTextColor", setTextColor },
	{ "DrawText", drawText },
	{ "UpdateEvent", updateEvent },
	{ "GetEventType", getEventType },
	{ "Pause", pause },
	{ "Sleep", sleep },
	{ "GetInitTime", getInitTime },
	{ "GetAccurateCount", getAccurateCount },
	{ "GetCounterFrequency", getCounterFrequency },
	{ "AddTimer", addTimer },
	{ "RemoveTimer", removeTimer },
	{ NULL, NULL }
};


extern "C" __declspec(dllexport)
int luaopen_QGame(lua_State * L)
{
	luaL_newlib(L, cMethods);
	return 1;
}